// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: geometry_msgs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position    *Point      `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Orientation *Quaternion `protobuf:"bytes,2,opt,name=orientation,proto3" json:"orientation,omitempty"`
}

func (x *Pose) Reset() {
	*x = Pose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geometry_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pose) ProtoMessage() {}

func (x *Pose) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pose.ProtoReflect.Descriptor instead.
func (*Pose) Descriptor() ([]byte, []int) {
	return file_geometry_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *Pose) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Pose) GetOrientation() *Quaternion {
	if x != nil {
		return x.Orientation
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geometry_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_geometry_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Quaternion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	W float64 `protobuf:"fixed64,4,opt,name=w,proto3" json:"w,omitempty"`
}

func (x *Quaternion) Reset() {
	*x = Quaternion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geometry_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quaternion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quaternion) ProtoMessage() {}

func (x *Quaternion) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quaternion.ProtoReflect.Descriptor instead.
func (*Quaternion) Descriptor() ([]byte, []int) {
	return file_geometry_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *Quaternion) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Quaternion) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Quaternion) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Quaternion) GetW() float64 {
	if x != nil {
		return x.W
	}
	return 0
}

type PoseWithCovariance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pose       *Pose     `protobuf:"bytes,1,opt,name=pose,proto3" json:"pose,omitempty"`
	Covariance []float64 `protobuf:"fixed64,2,rep,packed,name=covariance,proto3" json:"covariance,omitempty"`
}

func (x *PoseWithCovariance) Reset() {
	*x = PoseWithCovariance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geometry_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoseWithCovariance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoseWithCovariance) ProtoMessage() {}

func (x *PoseWithCovariance) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoseWithCovariance.ProtoReflect.Descriptor instead.
func (*PoseWithCovariance) Descriptor() ([]byte, []int) {
	return file_geometry_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *PoseWithCovariance) GetPose() *Pose {
	if x != nil {
		return x.Pose
	}
	return nil
}

func (x *PoseWithCovariance) GetCovariance() []float64 {
	if x != nil {
		return x.Covariance
	}
	return nil
}

type PoseWithCovarianceStamped struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Pose   *PoseWithCovariance `protobuf:"bytes,2,opt,name=pose,proto3" json:"pose,omitempty"`
}

func (x *PoseWithCovarianceStamped) Reset() {
	*x = PoseWithCovarianceStamped{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geometry_msgs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoseWithCovarianceStamped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoseWithCovarianceStamped) ProtoMessage() {}

func (x *PoseWithCovarianceStamped) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_msgs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoseWithCovarianceStamped.ProtoReflect.Descriptor instead.
func (*PoseWithCovarianceStamped) Descriptor() ([]byte, []int) {
	return file_geometry_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *PoseWithCovarianceStamped) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PoseWithCovarianceStamped) GetPose() *PoseWithCovariance {
	if x != nil {
		return x.Pose
	}
	return nil
}

type PoseStamped struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Pose   *Pose   `protobuf:"bytes,2,opt,name=pose,proto3" json:"pose,omitempty"`
}

func (x *PoseStamped) Reset() {
	*x = PoseStamped{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geometry_msgs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoseStamped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoseStamped) ProtoMessage() {}

func (x *PoseStamped) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_msgs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoseStamped.ProtoReflect.Descriptor instead.
func (*PoseStamped) Descriptor() ([]byte, []int) {
	return file_geometry_msgs_proto_rawDescGZIP(), []int{5}
}

func (x *PoseStamped) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PoseStamped) GetPose() *Pose {
	if x != nil {
		return x.Pose
	}
	return nil
}

var File_geometry_msgs_proto protoreflect.FileDescriptor

var file_geometry_msgs_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x1a, 0x0e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b,
	0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x2e, 0x51, 0x75, 0x61, 0x74, 0x65, 0x72, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x0b,
	0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x05, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79,
	0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x7a, 0x22, 0x44,
	0x0a, 0x0a, 0x51, 0x75, 0x61, 0x74, 0x65, 0x72, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x01, 0x7a, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x01, 0x77, 0x22, 0x5d, 0x0a, 0x12, 0x50, 0x6f, 0x73, 0x65, 0x57, 0x69, 0x74, 0x68,
	0x43, 0x6f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x70, 0x6f,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x65, 0x52, 0x04, 0x70,
	0x6f, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0a, 0x63, 0x6f, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x22, 0x7c, 0x0a, 0x19, 0x50, 0x6f, 0x73, 0x65, 0x57, 0x69, 0x74, 0x68, 0x43,
	0x6f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x65, 0x64,
	0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x04, 0x70, 0x6f,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x43, 0x6f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x04, 0x70, 0x6f, 0x73,
	0x65, 0x22, 0x60, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x65, 0x64,
	0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x70, 0x6f,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x65, 0x52, 0x04, 0x70,
	0x6f, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_geometry_msgs_proto_rawDescOnce sync.Once
	file_geometry_msgs_proto_rawDescData = file_geometry_msgs_proto_rawDesc
)

func file_geometry_msgs_proto_rawDescGZIP() []byte {
	file_geometry_msgs_proto_rawDescOnce.Do(func() {
		file_geometry_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_geometry_msgs_proto_rawDescData)
	})
	return file_geometry_msgs_proto_rawDescData
}

var file_geometry_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_geometry_msgs_proto_goTypes = []interface{}{
	(*Pose)(nil),                      // 0: geometry_msgs.Pose
	(*Point)(nil),                     // 1: geometry_msgs.Point
	(*Quaternion)(nil),                // 2: geometry_msgs.Quaternion
	(*PoseWithCovariance)(nil),        // 3: geometry_msgs.PoseWithCovariance
	(*PoseWithCovarianceStamped)(nil), // 4: geometry_msgs.PoseWithCovarianceStamped
	(*PoseStamped)(nil),               // 5: geometry_msgs.PoseStamped
	(*Header)(nil),                    // 6: std_msgs.Header
}
var file_geometry_msgs_proto_depIdxs = []int32{
	1, // 0: geometry_msgs.Pose.position:type_name -> geometry_msgs.Point
	2, // 1: geometry_msgs.Pose.orientation:type_name -> geometry_msgs.Quaternion
	0, // 2: geometry_msgs.PoseWithCovariance.pose:type_name -> geometry_msgs.Pose
	6, // 3: geometry_msgs.PoseWithCovarianceStamped.header:type_name -> std_msgs.Header
	3, // 4: geometry_msgs.PoseWithCovarianceStamped.pose:type_name -> geometry_msgs.PoseWithCovariance
	6, // 5: geometry_msgs.PoseStamped.header:type_name -> std_msgs.Header
	0, // 6: geometry_msgs.PoseStamped.pose:type_name -> geometry_msgs.Pose
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_geometry_msgs_proto_init() }
func file_geometry_msgs_proto_init() {
	if File_geometry_msgs_proto != nil {
		return
	}
	file_std_msgs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_geometry_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geometry_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geometry_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quaternion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geometry_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoseWithCovariance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geometry_msgs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoseWithCovarianceStamped); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geometry_msgs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoseStamped); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geometry_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geometry_msgs_proto_goTypes,
		DependencyIndexes: file_geometry_msgs_proto_depIdxs,
		MessageInfos:      file_geometry_msgs_proto_msgTypes,
	}.Build()
	File_geometry_msgs_proto = out.File
	file_geometry_msgs_proto_rawDesc = nil
	file_geometry_msgs_proto_goTypes = nil
	file_geometry_msgs_proto_depIdxs = nil
}
