// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: nav_msgs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapLoadTime uint64  `protobuf:"varint,1,opt,name=map_load_time,json=mapLoadTime,proto3" json:"map_load_time,omitempty"`
	Resolution  float32 `protobuf:"fixed32,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Width       uint32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height      uint32  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Origin      *Pose   `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *MapMetaData) Reset() {
	*x = MapMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nav_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMetaData) ProtoMessage() {}

func (x *MapMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_nav_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMetaData.ProtoReflect.Descriptor instead.
func (*MapMetaData) Descriptor() ([]byte, []int) {
	return file_nav_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *MapMetaData) GetMapLoadTime() uint64 {
	if x != nil {
		return x.MapLoadTime
	}
	return 0
}

func (x *MapMetaData) GetResolution() float32 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

func (x *MapMetaData) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapMetaData) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapMetaData) GetOrigin() *Pose {
	if x != nil {
		return x.Origin
	}
	return nil
}

// This represents a 2-D grid map, in which each cell represents the probability of occupancy.
type OccupancyGrid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Header header
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// MetaData for the map
	Info *MapMetaData `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// The map data, in row-major order, starting with (0,0).  Occupancy
	// probabilities are in the range [0,100].  Unknown is -1.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *OccupancyGrid) Reset() {
	*x = OccupancyGrid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nav_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OccupancyGrid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupancyGrid) ProtoMessage() {}

func (x *OccupancyGrid) ProtoReflect() protoreflect.Message {
	mi := &file_nav_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupancyGrid.ProtoReflect.Descriptor instead.
func (*OccupancyGrid) Descriptor() ([]byte, []int) {
	return file_nav_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *OccupancyGrid) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *OccupancyGrid) GetInfo() *MapMetaData {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *OccupancyGrid) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_nav_msgs_proto protoreflect.FileDescriptor

var file_nav_msgs_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x61, 0x76, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6e, 0x61, 0x76, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x0e, 0x73, 0x74, 0x64, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x67, 0x65, 0x6f, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xac, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x70, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6d, 0x61, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x2b, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x2e, 0x50, 0x6f, 0x73, 0x65, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x22, 0x78,
	0x0a, 0x0d, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x6e, 0x63, 0x79, 0x47, 0x72, 0x69, 0x64, 0x12,
	0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x61, 0x76, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x2e, 0x4d, 0x61, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x70, 0x62,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nav_msgs_proto_rawDescOnce sync.Once
	file_nav_msgs_proto_rawDescData = file_nav_msgs_proto_rawDesc
)

func file_nav_msgs_proto_rawDescGZIP() []byte {
	file_nav_msgs_proto_rawDescOnce.Do(func() {
		file_nav_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_nav_msgs_proto_rawDescData)
	})
	return file_nav_msgs_proto_rawDescData
}

var file_nav_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nav_msgs_proto_goTypes = []interface{}{
	(*MapMetaData)(nil),   // 0: nav_msgs.MapMetaData
	(*OccupancyGrid)(nil), // 1: nav_msgs.OccupancyGrid
	(*Pose)(nil),          // 2: geometry_msgs.Pose
	(*Header)(nil),        // 3: std_msgs.Header
}
var file_nav_msgs_proto_depIdxs = []int32{
	2, // 0: nav_msgs.MapMetaData.origin:type_name -> geometry_msgs.Pose
	3, // 1: nav_msgs.OccupancyGrid.header:type_name -> std_msgs.Header
	0, // 2: nav_msgs.OccupancyGrid.info:type_name -> nav_msgs.MapMetaData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nav_msgs_proto_init() }
func file_nav_msgs_proto_init() {
	if File_nav_msgs_proto != nil {
		return
	}
	file_std_msgs_proto_init()
	file_geometry_msgs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_nav_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nav_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OccupancyGrid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nav_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nav_msgs_proto_goTypes,
		DependencyIndexes: file_nav_msgs_proto_depIdxs,
		MessageInfos:      file_nav_msgs_proto_msgTypes,
	}.Build()
	File_nav_msgs_proto = out.File
	file_nav_msgs_proto_rawDesc = nil
	file_nav_msgs_proto_goTypes = nil
	file_nav_msgs_proto_depIdxs = nil
}
